import React, { useEffect, useState } from "react";
import { Info } from "lucide-react";
import { Tooltip, TooltipTrigger, TooltipContent } from "@/components/ui/tooltip";

// Import the custom logos
// TEMPORARILY HIDDEN - Uncomment to show logos again
// import logo1 from "@/assets/logo-1-ai-book.png";
// import logo2 from "@/assets/logo-2-raven.png";
// import logo3 from "@/assets/logo-3-ship.png";
// import logo4 from "@/assets/logo-4-oak-leaf.png";
// import logo5 from "@/assets/logo-5-flame.png";
// import logo6 from "@/assets/logo-6-r-arrow.png";
// import logo7 from "@/assets/logo-7-lotus.png";

export default function LogoOutcomeSection() {
  // TEMPORARILY HIDDEN - Uncomment to show logos again
  // const BRAND_LOGOS: Record<string, string> = {
  //   "logo1": logo1,
  //   "logo2": logo2,
  //   "logo3": logo3,
  //   "logo4": logo4,
  //   "logo5": logo5,
  //   "logo6": logo6,
  //   "logo7": logo7,
  // };

  // const LOGO_ORDER = Object.keys(BRAND_LOGOS);

  const OUTCOMES = [
    // Row 1
    { value: "13h → 1h", label: "Weekly Admin" },
    { value: "48-72h", label: "Faster Than Boards" },
    { value: "2-3×", label: "More Opportunities" },
    { value: "£52K-£67K", label: "Cost per Rep" },
    // Row 2
    { value: "10,000+", label: "Sources Tracked 24/7" },
    { value: "65% vs 23%", label: "First-Contact" },
    { value: "6-Week", label: "Payback" },
    { value: "+18.5%", label: "Client Growth" },
  ];

  // Computed, plausible explanations for hover tooltips
  const salaryLow = 42000; // £
  const salaryHigh = 52000; // £
  const employerOnCost = 0.24; // taxes, pension, NI etc.
  const toolsAnnual = 2400; // £ per rep
  const costLow = Math.round(salaryLow * (1 + employerOnCost) + toolsAnnual); // ≈ £54.5k
  const costHigh = Math.round(salaryHigh * (1 + employerOnCost) + toolsAnnual); // ≈ £66.9k
  const hoursPerYear = 52 * 40;
  const hourlyLow = costLow / hoursPerYear; // loaded hourly cost
  const hourlyHigh = costHigh / hoursPerYear;

  const nfCurrency = new Intl.NumberFormat("en-GB", { style: "currency", currency: "GBP", maximumFractionDigits: 0 });
  const nfHour = new Intl.NumberFormat("en-GB", { style: "currency", currency: "GBP", maximumFractionDigits: 0 });

  const outcomeExplanations: Record<string, string> = {
    "Weekly Admin": `~13h/week previously spent on board scraping, news scanning, enrichment and list‑building. BD AI surfaces and prioritises signals automatically ⇒ ≈1h/week manual triage left.`,
    "Faster Than Boards": `Signals detected within 0–2h from sources; job boards appear 2–3 days later ⇒ ≈48–72h advantage to first touch.`,
    "More Opportunities": `Pre‑intent signal coverage (hiring velocity, funding, expansions, leadership changes) yields ~50 qualified signals/week vs. ~20 from boards ⇒ ~2–3× more.`,
    "Cost per Rep": `${nfCurrency.format(costLow)}–${nfCurrency.format(costHigh)} p.a. (base £${salaryLow.toLocaleString()}–£${salaryHigh.toLocaleString()} × ${(1+employerOnCost).toFixed(2)} on‑cost + tools £${toolsAnnual.toLocaleString()}).`,
    "Sources Tracked 24/7": `>10,000 sources (boards, news, filings, social, tech signals) refreshed every 15 minutes.`,
    "First-Contact": `Warm pre‑intent signals ≈65% reply vs. cold outbound ≈23% ⇒ ~2.8× (Δ +42pp).`,
    "Payback": `Saved research time + extra meetings/placements generated by signals ⇒ <6‑week payback.`,
    "Client Growth": `More first touches earlier + better qualification shortens cycles ⇒ observed +18.5% client growth (YoY).`,
  };

  const [reduceMotion, setReduceMotion] = useState(false);
  useEffect(() => {
    setReduceMotion(window.matchMedia?.("(prefers-reduced-motion: reduce)").matches ?? false);
  }, []);

  return (
    <section className="relative py-12 sm:py-16 md:py-20 bg-gray-50">
      <div className="mx-auto max-w-6xl px-4 sm:px-6">
        <div className="relative bg-white rounded-2xl sm:rounded-3xl border border-gray-200 shadow-2xl overflow-hidden">

          <header className="relative text-center px-4 sm:px-6 pt-10 sm:pt-14 md:pt-16">
            <p className="inline-flex items-center rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1.5 text-xs font-medium text-brand-strong">Used by recruiting teams who got tired of being second</p>
            <h2 className="mt-5 sm:mt-6 text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-bold tracking-tight text-gray-900">Here's what changed when they made the switch</h2>
            <p className="mt-4 sm:mt-5 text-base sm:text-lg text-gray-600">No fluff — just what moved the needle.</p>
          </header>

          {/* LOGOS MARQUEE (Left ➜ Right) - Mobile Optimized */}
          {/* TEMPORARILY HIDDEN - Uncomment to show logos again
          <div className="relative px-3 sm:px-6 pt-6 sm:pt-8">
            <div className="pointer-events-none absolute inset-y-0 left-0 w-12 sm:w-24 bg-gradient-to-r from-white to-transparent" />
            <div className="pointer-events-none absolute inset-y-0 right-0 w-12 sm:w-24 bg-gradient-to-l from-white to-transparent" />

            <MarqueeRow
              items={LOGO_ORDER.map((k) => ({ type: "logo" as const, key: k }))}
              speed={45}
              direction="ltr"
              pauseOnHover={!reduceMotion}
              renderItem={(it) => (
                <LogoBubble key={it.key} label={it.key} src={BRAND_LOGOS[it.key]} />
              )}
            />
          </div>

          <div className="relative mx-3 sm:mx-6 my-5 sm:my-6">
            <div className="h-px w-full bg-gradient-to-r from-transparent via-black/10 to-transparent" />
          </div>
          */}

          {/* OUTCOMES MARQUEE (Right ➜ Left) - Mobile Optimized */}
          <div className="relative px-3 sm:px-6 py-8 sm:py-10 md:py-12">
            <div className="pointer-events-none absolute inset-y-0 left-0 w-12 sm:w-24 bg-gradient-to-r from-white to-transparent" />
            <div className="pointer-events-none absolute inset-y-0 right-0 w-12 sm:w-24 bg-gradient-to-l from-white to-transparent" />

            <MarqueeRow
              items={OUTCOMES.map((o, i) => ({ type: "outcome" as const, key: `kpi-${i}`, data: o }))}
              speed={32}
              direction="rtl"
              pauseOnHover={!reduceMotion}
              renderItem={(it) => (
                <OutcomeCard key={it.key} value={it.data.value} label={it.data.label} explanation={outcomeExplanations[it.data.label]}
                />
              )}
            />

            <div className="mt-7 sm:mt-8 flex flex-wrap justify-center gap-2 text-[10px] sm:text-[11px] text-gray-600 pb-4 sm:pb-6">
              <Pill>Copy-paste</Pill>
              <Pill>Tab-hopping</Pill>
              <Pill>Manual enrichment</Pill>
              <Pill>Duplicate data</Pill>
              <Pill>Context loss</Pill>
              <Pill>Slow handoffs</Pill>
            </div>
          </div>
        </div>
      </div>

      <style dangerouslySetInnerHTML={{
        __html: `
          @keyframes marqueeLTR { 0% { transform: translateX(-15%); } 100% { transform: translateX(-65%); } }
          @keyframes marqueeRTL { 0% { transform: translateX(-65%); } 100% { transform: translateX(-15%); } }
          ._track { width: 200%; display: flex; align-items: center; gap: 40px; }
          ._ltr { animation: marqueeLTR var(--spd, 36s) linear infinite; }
          ._rtl { animation: marqueeRTL var(--spd, 36s) linear infinite; }
        `
      }} />
    </section>
  );
}

function MarqueeRow<T extends { key: string }>(props: {
  items: T[];
  speed?: number;
  direction?: "ltr" | "rtl";
  pauseOnHover?: boolean;
  renderItem: (it: T) => React.ReactNode;
}) {
  const { items, speed = 36, direction = "ltr", pauseOnHover = true, renderItem } = props;
  const list = [...items, ...items];
  return (
    <div className="relative overflow-hidden">
      <div
        className={`_track ${direction === "ltr" ? "_ltr" : "_rtl"}`}
        style={{
          // @ts-ignore custom property for speed
          "--spd": `${speed}s`,
        }}
        onMouseEnter={(e) => {
          if (!pauseOnHover) return;
          (e.currentTarget as HTMLDivElement).style.animationPlayState = "paused";
        }}
        onMouseLeave={(e) => {
          if (!pauseOnHover) return;
          (e.currentTarget as HTMLDivElement).style.animationPlayState = "running";
        }}
      >
        {list.map((it, i) => (
          <div key={`${it.key}-${i}`} className="shrink-0">
            {renderItem(it)}
          </div>
        ))}
      </div>
    </div>
  );
}

function LogoBubble({ label, src }: { label: string; src?: string }) {
  const [error, setError] = useState(false);
  return (
    <div className="flex items-center justify-center transition-all hover:scale-110">
      {src && !error ? (
        <img
          src={src}
          alt={`Logo ${label}`}
          className="h-24 w-24 sm:h-28 sm:w-28 md:h-32 md:w-32 lg:h-36 lg:w-36 object-contain transition"
          onError={() => setError(true)}
        />
      ) : (
        <span className="flex h-24 w-24 sm:h-28 sm:w-28 md:h-32 md:w-32 lg:h-36 lg:w-36 items-center justify-center rounded-lg text-2xl font-semibold text-gray-400">?</span>
      )}
    </div>
  );
}

function OutcomeCard({ value, label, explanation }: { value: string; label: string; explanation?: string }) {
  return (
    <Tooltip>
      <TooltipTrigger asChild>
        <div className="relative group min-w-[140px] sm:min-w-[160px] md:min-w-[180px] rounded-xl sm:rounded-2xl border border-gray-200 bg-white hover:bg-gray-50 transition-all shadow-md hover:shadow-lg px-3 sm:px-4 md:px-5 py-3 sm:py-4 text-center cursor-help">
          <div className="text-xl sm:text-2xl md:text-3xl font-bold text-gray-900">{value}</div>
          <div className="text-[10px] sm:text-xs text-gray-600 mt-1 sm:mt-1.5 font-medium">{label}</div>
          <span className="absolute top-1.5 sm:top-2 right-1.5 sm:right-2 inline-flex h-4 w-4 sm:h-5 sm:w-5 items-center justify-center rounded-full bg-emerald-50 text-emerald-600 border border-emerald-200 shadow-sm transition group-hover:bg-emerald-100">
            <Info className="h-2.5 w-2.5 sm:h-3 sm:w-3" />
          </span>
        </div>
      </TooltipTrigger>
      {explanation ? (
        <TooltipContent side="top" className="max-w-xs text-left bg-gray-900 text-white border-gray-800">
          <div className="font-semibold">{value} — {label}</div>
          <div className="mt-1.5 text-xs opacity-90">{explanation}</div>
        </TooltipContent>
      ) : null}
    </Tooltip>
  );
}

function Pill({ children }: { children: React.ReactNode }) {
  return <span className="rounded-full bg-gray-100 border border-gray-300 px-3 py-1.5 text-xs font-medium text-gray-700">{children}</span>;
}


