import Reveal from "@/components/ui/reveal";
import { Tooltip, TooltipTrigger, TooltipContent } from "@/components/ui/tooltip";
import { Info } from "lucide-react";

interface StatsSectionProps {
  mode: "sales" | "recruitment";
}

export function StatsSection({ mode }: StatsSectionProps) {
  const stats = [
    // Row 1
    { number: "13h → 1h", label: "Weekly Admin" },
    { number: "48-72h", label: "Faster Than Boards" },
    { number: "2-3×", label: "More Opportunities" },
    { number: "£52K-£67K", label: "Cost per Rep" },
    // Row 2
    { number: "10,000+", label: "Sources Tracked 24/7" },
    { number: "65% vs 23%", label: "First-Contact" },
    { number: "6-Week", label: "Payback" },
    { number: "+18.5%", label: "Client Growth" }
  ];

  const explanations: Record<string, string> = {
    "Weekly Admin": "~13 h/week previously spent searching boards, scanning news, enrichment and list‑building. BD AI signal feed surfaces and prioritises leads automatically ⇒ ≈1 h/week manual triage left.",
    "Faster Than Boards": "Signals detected within 0–2 h vs job boards posting 2–3 days later ⇒ 48–72 h faster to first touch.",
    "More Opportunities": "Coverage of pre‑intent signals (hiring velocity, funding, expansions, leadership changes) yields 40–60 qualified signals/week vs. 18–22 via boards ⇒ ≈ 2–3× more.",
    "Cost per Rep": "£38–48k base + ~24% employer on‑cost + ~£2.4k tools/year ⇒ £52–67k.",
    "Sources Tracked 24/7": ">10,000 sources (boards, news, regulatory filings, social, tech signals) checked every 15 min.",
    "First-Contact": "Warm pre‑intent signals ≈65% reply vs. cold outbound ≈23% (n≈3–6k contacts).",
    "Payback": "Saved search time + extra meetings/placements generated by signals ⇒ <6‑week payback.",
    "Client Growth": "+18.5% from higher first‑touch rate × better qualification × shorter cycles (YoY).",
  };

  return (
    <section id="stats" className="py-20 bg-black text-center">
      <div className="max-w-6xl mx-auto px-10">
        <Reveal>
          <h2 className="text-3xl md:text-4xl font-bold mb-3 text-white">These aren’t vanity metrics</h2>
        </Reveal>
        <Reveal>
          <p className="text-white/70 mb-3">These are agencies making more placements with the same team size.</p>
          <p className="text-white/60 text-xs mb-10">Hover a card to see how it’s calculated.</p>
        </Reveal>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-8 md:gap-12">
          {stats.map((stat, index) => (
            <Reveal key={index} delay={index * 80}>
              <Tooltip>
                <TooltipTrigger asChild>
                  <div className="relative group p-6 border border-white/10 bg-white/5 rounded-xl cursor-help">
                    <div className="text-3xl md:text-4xl font-extrabold mb-2 text-white">{stat.number}</div>
                    <div className="text-sm md:text-base text-white/70">{stat.label}</div>
                    <span className="absolute top-2 right-2 inline-flex h-4 w-4 items-center justify-center rounded-full bg-white/10 text-white/70 border border-white/10 shadow-sm transition group-hover:text-white group-hover:bg-white/20">
                      <Info className="h-2.5 w-2.5 icon-pulse" />
                    </span>
                  </div>
                </TooltipTrigger>
                <TooltipContent side="top" className="max-w-xs text-left">
                  <div className="font-medium">{stat.number} — {stat.label}</div>
                  <div className="mt-1 text-xs opacity-80">{explanations[stat.label] ?? ""}</div>
                </TooltipContent>
              </Tooltip>
            </Reveal>
          ))}
        </div>
      </div>
    </section>
  );
}
